import { GamePreset } from '../types/game';

export const GAME_PRESETS: GamePreset[] = [
  {
    id: 'spaceship',
    title: 'Tàu Vũ Trụ Aegis-IV Gặp Nạn',
    tagline: 'Khoa học viễn tưởng • Sinh tồn không gian sâu • Cạn kiệt oxy',
    icon: '🚀',
    bannerColor: 'from-cyan-900 to-blue-950',
    world: 'Tàu thám hiểm không gian Aegis-IV trôi dạt vô định trong vành đai thiên thạch Zeta-9. Lò phản ứng nhiệt hạch quá tải, hệ thống hỗ trợ sự sống đếm ngược từng phút, còi báo động nhấp nháy đỏ rực trong bóng tối.',
    goal: 'Khởi động lại lõi năng lượng phụ, dập tắt rò rỉ bức xạ và kích hoạt khoang thoát hiểm trước khi lượng dưỡng khí cạn kiệt (dưới 60 phút).',
    defaultPlayers: [
      {
        id: 'P1',
        name: 'Trần Bách',
        role: 'Bác sĩ Cứu Thương Trạm',
        avatarIcon: '🩺',
        quickActions: [
          'Tiêm thuốc trợ tim khẩn cấp cho đồng đội',
          'Đo nồng độ bức xạ và phát mặt nạ oxy',
          'Tìm kiếm tủ thuốc dự phòng trong khoang y tế',
        ],
      },
      {
        id: 'P2',
        name: 'Lê Tuấn',
        role: 'Kỹ sư Cơ Khí & Điện Lực',
        avatarIcon: '🔧',
        quickActions: [
          'Dùng mỏ hàn cắt khóa cửa bị kẹt',
          'Đấu tắt bảng mạch rơ-le để cấp điện khoang điều khiển',
          'Kiểm tra ống dẫn khí nén làm mát lò phản ứng',
        ],
      },
      {
        id: 'P3',
        name: 'Phan Lâm',
        role: 'Trinh sát & Xạ thủ Hạm Đội',
        avatarIcon: '🎯',
        quickActions: [
          'Cầm súng điện áp sát góc tối dò quét sinh vật lạ',
          'Trèo qua đường ống thông gió sang phòng chỉ huy',
          'Quan sát qua camera giám sát tìm đường thoát',
        ],
      },
      {
        id: 'P4',
        name: 'Tiến sĩ Mai Chi',
        role: 'Học giả AI & Chuyên gia Dữ Liệu',
        avatarIcon: '💻',
        quickActions: [
          'Hack máy chủ AI Mẹ để tải nhật ký hải trình',
          'Vượt qua tường lửa giải mã mã phóng tàu cứu hộ',
          'Phân tích bản đồ thiết kế kiến trúc tàu',
        ],
      },
    ],
    defaultInventory: ['Đèn pin quân dụng', 'Bình oxy mini (20 phút)', 'Dụng cụ sửa chữa đa năng', 'Hộp sơ cứu tiệt trùng'],
    initialTime: '00:00 AM | Nồng độ Oxy: 85%',
  },
  {
    id: 'haunted_mansion',
    title: 'Bí Ẩn Biệt Thự Ma Ám Blackwood',
    tagline: 'Kinh dị huyền bí • Giải đố cổ kính • Lời nguyền bóng đêm',
    icon: '🏚️',
    bannerColor: 'from-purple-950 to-slate-950',
    world: 'Biệt thự cổ dòng họ Blackwood nằm biệt lập giữa khu rừng sương mù dày đặc. Sau tiếng sét đánh trúng tháp chuông, cánh cửa chính tự động khóa chặt bằng ổ xích thép. Tiếng thì thầm lạnh gáy vang vọng khắp các bức tường phủ đầy mạng nhện.',
    goal: 'Giải mã bí ẩn cái chết của gia chủ, thu thập đủ 3 mảnh Chìa Khóa Quỷ và mở cánh cửa tầng hầm thoát ra ngoài trước 12:00 đêm.',
    defaultPlayers: [
      {
        id: 'P1',
        name: 'Thầy thuốc An',
        role: 'Bác sĩ Pháp y & Thảo Dược',
        avatarIcon: '🧪',
        quickActions: [
          'Khám nghiệm vết tích kỳ lạ trên sàn gỗ',
          'Đốt nén hương xua đuổi chướng khí độc hại',
          'Băng bó vết cào rỉ máu cho đồng đội',
        ],
      },
      {
        id: 'P2',
        name: 'Hoàng Thợ Khóa',
        role: 'Kỹ sư Cơ Quan & Bẻ Khóa',
        avatarIcon: '🗝️',
        quickActions: [
          'Dùng bộ ghim móc ổ khóa tủ ngăn kéo cổ',
          'Gõ tường kiểm tra lối đi bí mật sau giá sách',
          'Chặn cửa gỗ bằng thanh xà sắt đề phòng quỷ dữ',
        ],
      },
      {
        id: 'P3',
        name: 'Vũ Thám Tử',
        role: 'Trinh sát Hiện Trường',
        avatarIcon: '🔦',
        quickActions: [
          'Dùng đèn UV soi vết chân phát quang',
          'Cầm gậy bóng chày đứng cảnh giới góc cầu thang',
          'Lắng nghe tiếng bước chân kỳ lạ sau vách ngăn',
        ],
      },
      {
        id: 'P4',
        name: 'Học giả Linh',
        role: 'Nhà Cổ Ngữ & Huyền Học',
        avatarIcon: '📜',
        quickActions: [
          'Đọc to câu thần chú xua đuổi tà linh trong cuốn nhật ký',
          'Giải mã bức tranh chân dung có đôi mắt chuyển động',
          'Tra cứu gia phả dòng họ tìm điểm yếu của linh hồn',
        ],
      },
    ],
    defaultInventory: ['Đèn bão dầu hỏa', 'Gương soi trừ tà', 'Bó nến trắng & Diêm', 'Cuốn nhật ký rách góc'],
    initialTime: '10:45 PM | Chìa khóa: 0/3',
  },
  {
    id: 'desert_island',
    title: 'Đảo Hoang Sinh Tồn: Răng Cá Mập',
    tagline: 'Sinh tồn dã ngoại • Thú săn mồi nhiệt đới • Bí ẩn đền cổ',
    icon: '🏝️',
    bannerColor: 'from-emerald-950 to-stone-900',
    world: 'Sau cơn bão biển dữ dội đánh chìm con tàu viễn chinh, 4 người dạt vào một bãi cát đen bao quanh bởi những mỏm đá nhọn như răng cá mập. Phía sâu trong rừng rậm nhiệt đới vang lên tiếng gầm gừ man rợ của những sinh vật chưa từng thấy.',
    goal: 'Sinh tồn qua đêm, tìm nguồn nước ngọt, dựng pháo đài trú ẩn và nhóm ngọn lửa khổng lồ trên đỉnh núi đá để tàu cứu hộ phát hiện.',
    defaultPlayers: [
      {
        id: 'P1',
        name: 'Hương Bác Sĩ',
        role: 'Bác sĩ Dã Chiến & Dược Học',
        avatarIcon: '🌿',
        quickActions: [
          'Hái lá thuốc giã nát đắp vết cắn nhiễm trùng',
          'Chưng cất nước ngọt từ nước biển và lá chuối',
          'Kiểm tra nọc độc của quả rừng nhặt được',
        ],
      },
      {
        id: 'P2',
        name: 'Quân Thợ Rèn',
        role: 'Kỹ sư Chế Tác & Bẫy Cọc',
        avatarIcon: '🪓',
        quickActions: [
          'Chặt tre nứa chế tạo rìu đá và giáo nhọn',
          'Dựng giàn che lều trú ẩn chống mưa bão',
          'Đan bẫy cá dọc theo con lạch ven rừng',
        ],
      },
      {
        id: 'P3',
        name: 'Sơn Thợ Săn',
        role: 'Trinh sát Dấu Vết & Thiện Xạ',
        avatarIcon: '🏹',
        quickActions: [
          'Leo lên ngọn cây dừa cao quan sát địa hình đảo',
          'Lần theo dấu chân thú móng vuốt trong bùn',
          'Cầm giáo nhọn đứng gác hướng gió cảnh giác thú dữ',
        ],
      },
      {
        id: 'P4',
        name: 'Tiến sĩ Vân',
        role: 'Nhà Địa Chất & Thời Tiết',
        avatarIcon: '🧭',
        quickActions: [
          'Quan sát hướng mây và sao trời dự báo áp thấp nhiệt đới',
          'Dùng la bàn cổ tìm vỉa đá chứa nguồn nước ngầm',
          'Đọc ký hiệu khắc trên tảng đá cự thạch ven bờ',
        ],
      },
    ],
    defaultInventory: ['Đá lửa đánh tia', 'Dao găm gỉ sét', 'Dây thừng gai 10m', 'Tấm bạt che mưa rách'],
    initialTime: 'Chiều tà 17:30 | Nước ngọt: Cạn kiệt',
  },
  {
    id: 'fantasy_dungeon',
    title: 'Hầm Ngục Bí Mật: Vương Quốc Cổ Draken',
    tagline: 'Kỳ ảo ma thuật • Hầm mộ cổ tích • Rồng canh giữ',
    icon: '🧙‍♂️',
    bannerColor: 'from-amber-950 to-neutral-950',
    world: 'Nhóm thám hiểm bước qua cánh cổng đá cổ đại dẫn sâu xuống mê cung ngầm Drakenheim. Những ngọn đuốc xanh ma quái tự bốc cháy dọc theo lối đi lát đá cổ, nơi cất giấu Trái Tim Rồng huyền thoại được bảo vệ bởi những chiến binh bù nhìn ma thuật.',
    goal: 'Vượt qua 3 tầng bẫy ngầm, giải trừ bùa phong ấn cổ xưa và đoạt lại Trái Tim Rồng trước khi thế lực bóng tối thức tỉnh hoàn toàn.',
    defaultPlayers: [
      {
        id: 'P1',
        name: 'Minh Quang',
        role: 'Mục Sư Thánh Quang',
        avatarIcon: '✨',
        quickActions: [
          'Thi triển Thánh Quang trị liệu vết thương cho cả đội',
          'Tạo lá chắn hộ thể ngăn chặn ma thuật hắc ám',
          'Cầu nguyện xua tan khí độc trong hầm mộ',
        ],
      },
      {
        id: 'P2',
        name: 'Đạt Thiết Giáp',
        role: 'Đấu Sĩ & Kỹ Sư Cơ Giới Cổ',
        avatarIcon: '🛡️',
        quickActions: [
          'Giơ đại khiên sắt chắn luồng tên bắn từ bẫy vách đá',
          'Dùng xà beng chèn bánh răng cơ quan hạ cầu treo',
          'Vung chùy tạ đập vỡ tượng đá canh cửa',
        ],
      },
      {
        id: 'P3',
        name: 'Phong Dạ Hành',
        role: 'Đạo Tặc & Trinh Sát Ám Ảnh',
        avatarIcon: '🗡️',
        quickActions: [
          'Rón rén dò bẫy áp lực trên gạch lát sàn',
          'Ẩn mình trong bóng tối ném phi tiêu đánh lạc hướng',
          'Dùng dây móc đu qua hố sâu chông nhọn',
        ],
      },
      {
        id: 'P4',
        name: 'Thảo Ma Pháp',
        role: 'Pháp Sư Bí Thuật & Cổ Ngữ',
        avatarIcon: '🔮',
        quickActions: [
          'Bắn tia sét ma pháp kích hoạt viên ngọc phong ấn',
          'Đọc cổ ngữ khắc trên tường rồng tìm lời giải câu đố',
          'Triệu hồi cầu lửa xua đuổi nhện khổng lồ',
        ],
      },
    ],
    defaultInventory: ['Bình máu thánh dược x2', 'Đuốc ma thuật bất tử', 'Bản đồ da cừu cổ', 'Bột phát hiện cơ quan ngầm'],
    initialTime: 'Tầng 1 Hầm Mộ | Phong ấn: 1/3',
  },
];
